### ISSUE TITLE
Including `jsx` files?

### ISSUE THREAD

**Issue by agibralter** [prontolabs/pronto-eslint#15]
Is there any chance `jsx` could be added to this [list](https://github.com/mmozuras/pronto-eslint/blob/master/lib/pronto/eslint.rb#L45)? Or perhaps an ENV variable that could be set to allow for additional files to be recognized?

**Comment by mmozuras** [comment]
@agibralter it could, I'm just not familiar enough with eslint to be sure if that makes sense 😄. Is there a chance of false-positives, if we would do that?

@hlascelles @doits @pmvrmc what do you think?

**Comment by pmvrmc** [comment]
Sorry for the late response, I think that adding jsx would be great! A lot of people nowadays use react, however I'm not sure the eslint version eslintrb is using supports it. Do you know?
@agibralter @mmozuras @hlascelles @doits

**Comment by hlascelles** [comment]
So, a quick check and... yes, it works. Our React files have the ending `.js`, but I'm sure that's just a detail. `pronto-eslint` parses and reports errors just fine. I'd say add it!

**Comment by mmozuras** [comment]
Done!

Released as [v0.9.1](https://github.com/mmozuras/pronto-eslint/releases/tag/v0.9.1).

**Comment by doits** [comment]
Might be an idea to make the file suffixes configurable (with a reasonable default) like I did in https://github.com/doits/pronto-eslint_npm, then everybody can lint whatever files he wishes.
