### ISSUE TITLE
Support `.eslintrc.*` configuration files

### ISSUE THREAD

**Issue by ldelbeccaro** [prontolabs/pronto-eslint#16]
ESLint [configuration instructions](https://eslint.org/docs/user-guide/configuring) say to use [any of these `.eslintrc.*` formats](https://eslint.org/docs/user-guide/configuring#configuration-file-formats); it seems like `.eslintrc` is actually being deprecated.

I had to rename my `.eslintrc.json` file to the deprecated `.eslintrc` to get my config options to work correctly.

**Comment by doomspork** [comment]
Thanks for the heads up @ldelbeccaro!  Would you be interested in opening a PR for these changes?

**Comment by mmozuras** [comment]
@ldelbeccaro thanks!

We would actually need to update [eslintrb](https://github.com/zendesk/eslintrb) first. 
An alternative to using `pronto-eslint`, is to use [pronto-eslint_npm](https://github.com/doits/pronto-eslint_npm), which does not depend on Zendesk's ruby gem.

**Comment by ashkulz** [comment]
I think this runner is effectively obsolete as eslintrb hasn't been updated since 2016.
