### ISSUE TITLE
Pronto fails on .eslintrc

### ISSUE THREAD

**Issue by prostko** [prontolabs/pronto-eslint#17]
Recently updated my app to include webpacker and webpacker-vue. 

now running pronto returns:
`.eslintrc: F: Parsing error: Unexpected token import`

Is it possible to prevent linting on  the `.eslintrc` file?

**Comment by aardvarkk** [comment]
I believe this is a red herring. I dug into the eslintrb code and found that they default to saying the filename is `.eslintrc` if the error is fatal. No idea why... but that's what the code does. I had the same issue. I ended up setting a breakpoint in the eslintrb code (called by pronto-eslint) so I could look at the actual offences and figure out where they came from.

**Comment by ashkulz** [comment]
I think this runner is effectively obsolete as eslintrb hasn't been updated since 2016.

**Comment by theotherdon** [comment]
FYI, this is actually a bug in pronto-eslint. I opened up a WIP PR that mostly fixes this issue #23. However, I'm still working through trying to get a couple of tests to pass.
