### ISSUE TITLE
Loading (parsing) of .eslintrc (json) is not working as expected

### ISSUE THREAD

**Issue by abinoam** [prontolabs/pronto-eslint#4]
I have figured out that the format suggested at https://github.com/zendesk/eslintrb/blob/master/README.md is not JSON.parse compatible.

Issueing a PR over there in a minute.
Opening an issues here as zendesk/eslintrb is not open for issues. 
And to make you (@mmozuras) aware of the issue.

**Comment by mmozuras** [comment]
@abinoam closing, as it's not really a pronto-eslint issue and it should be fixed after your PR is merged: https://github.com/zendesk/eslintrb/pull/4
(you only need to fix the one comment 😄)
