### ISSUE TITLE
Support for `.eslintignore`

### ISSUE THREAD

**Issue by doits** [prontolabs/pronto-eslint#6]
It would be nice if the [.eslintignore](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories) was respected.

**Comment by mmozuras** [comment]
@doits it seems a better fit to handle it on [eslintrb](https://github.com/zendesk/eslintrb) instead of Pronto? Have you considered it?

**Comment by doits** [comment]
Yeah, maybe that's a better place. But since I am now using my own runner https://github.com/doits/pronto-eslint_npm, where it works out of the box, I do not need this any more in here or in eslintrb.
